
language: python
python:
  - "2.7"
  - "3.4"
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
install: pip install discover
script: python -m unittest discover tests "test_*.py"
branches:
  only:
    - master
