
language: python
python:
  - "2.7"
  - "3.4"

install: pip install discover
before_install:
  - sudo apt-get update && sudo apt-get --reinstall install -qq language-pack-fr
script: python -m unittest discover tests "test_*.py"
branches:
  only:
    - master
