
#+BABEL: :comments no
#+VERSION: 0.2.0a

#+ATTR_HTML: :alt builstatus image :title travis :align left
* pyorgmode [[https://api.travis-ci.org/flintforge/pyorgmode.svg?branch=master]]
pyorgmode is python module to read, manipulate, and produce org-mode files.


v0.2.0 is a fork of this [[https://github.com/bjonnh/PyOrgMode][PyOrgMode]] and a rewrite in a more "pythonic" style.

We would like to thank all the people who contribute.


** Installation

Download the git repo, install the package.
#+BEGIN_SRC sh
git clone https://github.com/flintforge/pyorgmode.git
cd pyorgmode && python setup.py install
#+END_SRC

** tests
to run the test suite
#+BEGIN_SRC python
python -m unittest discover tests "test_*.py"
#+END_SRC
** development on ipython
#+BEGIN_SRC python
'''
enable autoreload of the lib whenever a change occurs
'''
%load_ext autoreload
%autoreload 2
%aimport pyorgmode
# set the locale for correct date handling (%a)
import locale
locale.setlocale(locale.LC_TIME, "")
# you'll need it to properly handle
# date format such as <2017-03-24 Fri>
# or <2017-03-24 ven.>

from pyorgmode import *

org = OrgDataStructure()
org.load_from_file("tests/orgs/test.org")
topnodes = org.toplevel_nodes()
headings = [T.heading for T in topnodes]
print(headings)
for it in topnodes :
    print (it.level, it.todo, it.priority, it.heading, it.tags)
#+END_SRC



* TODO [1/8]
- [-] Tests [1/3]
   - [X] Move tests to separate directory
   - [ ] Check for other OS compatibility
   - [ ] provide a bigger and more extensive test.org

- [-]  OrgDate [1/5]
   - [X] support LC_DATE locale
   - [ ] multilocale / strpdate format in one file
   - [ ] or inline locale conversions ([[http://babel.pocoo.org/en/latest/locale.html][babel]] ?)
   - [ ] enforce date validation (99:99)
   - [ ] recurrent events (+1w …)

- [ ] OrgList
- [ ] OrgProtocol
- [ ] OrgTable
- [ ] Table edition 
   - separators, cell length, length calculator…

- [-] OrgNode [0/2]
   - [ ] scheduling in orgnode header
   - [ ] test all get_by_attributes()

- [X] more Pep8 conformancy


** Authors

#+begin_src ascii :tangle AUTHORS :exports code
Phil ESTIVAL <flint at forge.systems> : maintain this repository
Jonathan BISSON <firstname.lastname at bjonnh.net> : initiator of the project
Antti KAIHOLA <akaihol plus orgmode at ambitone dot com>
credits to m3wolf, bordercore, wroberts, gonvaled, 10nin, CodeMonk, midraal, whacked
#+end_src
